const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "./images/shirt1.jpg",
      countInStock: 10,
      price: 48,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Cotton 100%",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "./images/pant1.jpg",
      countInStock: 10,
      brand: "Nike",
      price: 20,
      rating: 4.5,
      numReviews: 10,
      description: "Cotton 100%",
    },
    {
      name: "Nike Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "./images/shirt2.jpg",
      countInStock: 10,
      price: 45,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Cotton 100%",
    },
    {
      name: "Adidas Slim Shirt",
      slug: "Adidas-slim-shirt",
      category: "Pants",
      image: "./images/pant2.jpg",
      countInStock: 10,
      price: 65,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "Cotton 100%",
    },
  ],
};

export default data;
